### ISSUE TITLE
Could Not Resolve Host

### ISSUE THREAD

**Issue by mztlive** [amphp/dns#103]
After I introduce amp/dns through composer, curl will trigger the exception "could resolve not host(6)" (occasionally)

But it’s strange that I just introduced it, but didn’t use it in the code.

After removing amp/dns from the composer dependency, it returned to normal

**Comment by kelunik** [comment]
If you didn't use the code, it was probably some other temporary error?

**Comment by mztlive** [comment]
> If you didn't use the code, it was probably some other temporary error?
I don’t know. To be precise, I introduced amp/php into composer and then occasionally could not resolve host using guzzlehttp.

When I removed amp/php, it returned to normal

**Comment by mztlive** [comment]
> If you didn't use the code, it was probably some other temporary error?


I don’t know. To be precise, I introduced amp/php into composer and then occasionally could not resolve host using guzzlehttp.

When I removed amp/php, it returned to normal

**Comment by mztlive** [comment]
> If you didn't use the code, it was probably some other temporary error?

I don’t know. To be precise, I introduced amp/http-client into composer and then occasionally could not resolve host using guzzlehttp.

When I removed amp/php, it returned to normal

**Comment by kelunik** [comment]
I'm closing this in favor of https://github.com/amphp/http-client/issues/293.
