### ISSUE TITLE
DNS resolution failed -- possibly cache bug

### ISSUE THREAD

**Issue by thomaswilde** [amphp/dns#16]
We get an `Amp\Dns\ResolutionException` with the message

    "DNS resolution failed: www.google.com"

These are the last couple of lines from our stack-trace:

    #0 ...\vendor\amphp\dns\lib\Client.php(298): Amp\Dns\Client->completePendingLookup(0, NULL, 3)
    #1 ...\vendor\amphp\dns\lib\Client.php(220): Amp\Dns\Client->completeRequest(Array, NULL, 3)
    #2 ...\vendor\amphp\amp\lib\NativeReactor.php(184): Amp\Dns\Client->Amp\Dns\{closure}(Object(Amp\NativeReactor), 2)
    #3 ...\vendor\amphp\amp\lib\NativeReactor.php(123): Amp\NativeReactor->executeAlarms()

It seems that the problem originates in `lib/Client.php` on line 311 where `$cacheHit` is `true` but `$addr` is `NULL`. Google is reachable by DNS from the environment in question.

**Comment by kelunik** [comment]
A non-blocking `amphp/cache` is now a thing. Using the php-fig interface doesn't make any sense for us, because have to use other method signatures anyway (everything returns a promise).

The only shared driver currently implemented is Redis.

**Comment by kelunik** [comment]
We have a TCP retry now if it fails with UDP. Closing for now.

**Comment by pensiero** [comment]
Same problem here, someone could explain me how can I cache the DNS resolution? I'm using Redis, and I saw that there is `amphp/redis`, but I don't understand how to use it with DNS.

Thanks

**Comment by kelunik** [comment]
DNS records are currently automatically cached in an `ArrayCache` according to their TTL. There's currently no way to specify another cache method.
