### ISSUE TITLE
Default nameservers without port 

### ISSUE THREAD

**Issue by tck** [amphp/dns#24]
If google's public DNS servers on Windows is used following error occurs:

    Fatal error: Uncaught exception 'Amp\Dns\ResolutionException' with message 'Connection to udp://8.8.8.8 failed: [Error #0] Failed to parse address "8.8.8.8"'

The default nameservers setting:

    "nameservers" => [
        "8.8.8.8",
        "8.8.4.4",
    ],

A correction could be setting port value:

    "nameservers" => [
        "8.8.8.8:53",
        "8.8.4.4:53",
    ],

**Comment by kelunik** [comment]
Thanks. Could you test with the latest `dev-master`? It should work, I just want to be sure before tagging a new release.

**Comment by staabm** [comment]
Sounds like this is a php-src inconsistency of win vs. *nix ?

**Comment by kelunik** [comment]
@staabm: What should be a `php-src` inconsistency here?

**Comment by staabm** [comment]
The initial report reads like the code (before your referenced commit) worked before on non-windows and doesnt on *nix

**Comment by kelunik** [comment]
Yes, because we read the `resolv.conf` on Linux, but that doesn't exist on Windows. It's really complicated on Windows to read those settings.

**Comment by tck** [comment]
Testet with the last dev-master. It works on my windows system. Thank you for the fast reaction.

**Comment by kelunik** [comment]
Thanks for the verification, [`0.8.4`](https://github.com/amphp/dns/releases/tag/v0.8.4) has been tagged.
