### ISSUE TITLE
isValidHostname throws exception on valid hostnames

### ISSUE THREAD

**Issue by chrisleavoy** [amphp/dns#34]
https://github.com/amphp/dns/blame/master/lib/DefaultResolver.php#L87

2.0.0.127.b.barracudacentral.org is a prefectly valid hostname that doesn't match the regex.

Suggest instead:

```php
$pattern = "/^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$/i";
```

It appears the top answer on stackoverflow is wrong: http://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address

**Comment by bwoebi** [comment]
Note that we have two functions, query() and resolve(). The latter one is explicitly for _hostname/IP_ (as defined per RFC 1123 2.1) resolving (will check /etc/hosts too and recurses (CNAME) by default), the former for arbitrary name resolving.

Just use query() if you want to resolve that one.

**Comment by bwoebi** [comment]
I shall maybe change the error message to explicitly reference RFC 1123 2.1 and give a hint at the query() function though...

**Comment by kelunik** [comment]
@bwoebi: That one is a valid hostname. It's not a documentation issue, it's a RegEx issue.

**Comment by bwoebi** [comment]
Oh, you are right. Will fix that then.

**Comment by kelunik** [comment]
@bwoebi You wanted to work on it, is that still the case?

**Comment by bwoebi** [comment]
Sorry for the delay… Forgotten about it and only rediscovered it today.
