### ISSUE TITLE
Possible infinite loop

### ISSUE THREAD

**Issue by kelunik** [amphp/dns#39]
From reading the source at https://github.com/amphp/dns/blob/55de45b00bc1d913a12d5e1574f1f36be4c901de/lib/DefaultResolver.php#L170-L176 it seems like this _might_ run into an infinite loop, once `MAX_REQUEST_ID` requests have been lost due to UDP being used?

**Comment by bwoebi** [comment]
Looks like we are not unset()ting the pendingRequest entry upon timeout failure or when falling back to TCP.

**Comment by kelunik** [comment]
But doesn't it also run into an infinite loop if there are `MAX_REQUEST_ID` concurrent requests?

**Comment by kelunik** [comment]
Fixed in the Amp v2 version.
