### ISSUE TITLE
Google Fallback

### ISSUE THREAD

**Issue by kelunik** [amphp/dns#42]
Currently we fallback to Google's public DNS servers if we don't have a config. This affected probably only Windows, as we don't have `/etc/resolv.conf` there. On other systems, that could only happen if there is an error reading `/etc/resolv.conf`.

I don't like sending all DNS queries silently as a fallback to Google. If the system config can't be read, it's either a weird system not yet supported (a bug then), or something other that has to be fixed on the system. @DaveRandom mentioned he'd like to keep the fallback, as we can still continue resolving domain names, but would like to issue a warning when the default config is used.

#40 plans to deprecate the default config and I plan to remove default nameservers when we release a new major version based on Amp v2.

Please add a :+1: if you want to drop the fallback, add a :-1: if you want to keep the fallback.

**Comment by Danack** [comment]
If someone explicitly sets the config, then it shouldn't do the fallback; it should behave exactly as they set the config.

If someone doesn't explicitly set the config, then people just want it to work and so the code should do the best attempt to work.

> I don't like sending all DNS queries silently as a fallback to Google.

I trust with my DNS lookups (aka think they are less likely to care about them) than I do my ISP, that is far more likely to be in cahoots with GCHQ or other industrial espionage.

**Comment by kelunik** [comment]
We could also factor it out to a `WindowsConfigReader`, `BindConfigReader` and fallback to a `EnvConfigReader` that reads from a environment variable. This ensures you can always set the DNS nameserver in any application in case your system is weird.

We could also prioritize the environment variable / use it as fallback without the above.

**Comment by bwoebi** [comment]
There's no point in factoring that out...

Also env variables, if we support them, should take priority in any case.

**Comment by kelunik** [comment]
> There's no point in factoring that out...

Accept if you want to fetch the information from another source, but that's not required I guess.

**Comment by kelunik** [comment]
The man page mentions environment variables for options and local domain, but not for nameservers. http://man7.org/linux/man-pages/man5/resolv.conf.5.html

**Comment by kelunik** [comment]
Related: https://twitter.com/fudoreaper/status/873926204046405632

**Comment by kelunik** [comment]
The Google fallback has been removed in the Amp v2 version.
