### ISSUE TITLE
Tests fail with OPCache enabled

### ISSUE THREAD

**Issue by kelunik** [amphp/dns#58]
Quite a few tests fail with OPCache enabled, because `Socket::ask` yields an empty array instead of an instance of `Message`.

**Comment by kelunik** [comment]
"Solved" by https://github.com/amphp/dns/commit/e0fc018ad7473cd24b188323393476c5a19a6d35.

**Comment by PeeHaa** [comment]
Is this (`return yield`) an issue in general with opcache or just this specific piece of code?

**Comment by kelunik** [comment]
It's a general issue with opcache + `return` in `try` + `finally`.

**Comment by bwoebi** [comment]
But just within Generators.

**Comment by PeeHaa** [comment]
kk tnx both ❤️
