### ISSUE TITLE
BasicResolver configLoader parameter

### ISSUE THREAD

**Issue by far-blue** [amphp/dns#62]
Hello :)

There's an issue with the setting of the configLoader in the BasicResolver constructor where incorrect precedence means the constructor always assigns a WindowsConfigLoader if you try to supply your own.

PR #61 fixes this

**Comment by kelunik** [comment]
Already merged. :+1:

**Comment by far-blue** [comment]
would it be possible to roll a release containing this merge? If a release will be some time distant I'd need to pin our composer config to a master commit which I really prefer not to do :)

**Comment by kelunik** [comment]
Sure.
