### ISSUE TITLE
Limit cache size by default

### ISSUE THREAD

**Issue by kelunik** [amphp/dns#65]
See https://github.com/amphp/cache/issues/4.

**Comment by kelunik** [comment]
The linked issue has been implemented, what's a good default cache size?

**Comment by kelunik** [comment]
@amphp/dns Any suggestions?

**Comment by bwoebi** [comment]
Don't really know.
I think a LRU cache with size=256 should be really sufficient for most needs. That's not too large, but really not less than 99% of use cases will need.

**Comment by Danack** [comment]
If it's a LRU cache, it should be way bigger than 256. Memory is pretty cheap and the entries are pretty small, right?

Is there any problem with having a 64kB entry cache?

**Comment by bwoebi** [comment]
I meant 256 entries ;-), which, in PHP, will be around 80 KB, I guess.
