### ISSUE TITLE
Support for extended macOS configurations

### ISSUE THREAD

**Issue by mmenozzi** [amphp/dns#69]
As stated at https://github.com/amphp/artax/issues/150, it seems that macOS resolver looks at `/etc/resolver` directory to get the nameserver to use for a certain TLD. For example if you put the file `/etc/resolver/dev`  with content `127.0.0.1`, the local nameserver will be used for all the `*.dev` domains.

This behavior should be supported by this library.

**Comment by kelunik** [comment]
Just a note for future readers: This requires a configuration format change and is therefore a BC break. It might be considered to implement this in the same release as #70, but that one might not need a BC break depending on the solution.
