### ISSUE TITLE
Bump the minimum version of amphp/uri

### ISSUE THREAD

**Issue by PeeHaa** [amphp/dns#79]
Currently the [minimum supported version of `amphp/uri` in composer](https://github.com/amphp/dns/blob/master/composer.json#L43) uses a broken version: `^1.0`.

> TypeError: Return value of Amp\Uri\Uri::getQueryParameter() must be of the type string, null returned

Can this be bumped to at least version `^0.1.1`, but probably better to just use latest.

Bonus internet points if the above change is topped off with a fresh release containing the change <3

**Comment by kelunik** [comment]
PR is welcome 😉

**Comment by trowski** [comment]
Seems we really only use the `uri` package for the `normalizeDnsName` function. Should we drop this function into `socket` or some other package and deprecate the `uri` package? We also may be able to use `league/uri`.

**Comment by PeeHaa** [comment]
If that's the case that would be much nicer indeed  
Looking at the function itself it could even be just included directly in dns
Or is the normalization done in other packages as well?

**Comment by trowski** [comment]
Closing since we dumped the `amphp/uri` dependency.
