### ISSUE TITLE
Subtype 'Too many redirects' DnsException

### ISSUE THREAD

**Issue by psafarov** [amphp/dns#90]
https://github.com/amphp/dns/blob/493d014b58c14e29303a145b0be4cf272aa6644f/lib/Rfc1035StubResolver.php#L219

It would be very nice to differentiate this type of error. In my situation this difference is important as other DnsException throws are usually temporary, so the script can be rerun successfully whereas 'Too many redirections' error tend to be permanent (e.g. if there is a cyclic aliasing)

**Comment by kelunik** [comment]
Do you want to provide a PR?
