### ISSUE TITLE
Libdns bug

### ISSUE THREAD

**Issue by psafarov** [amphp/dns#92]
There is a bug in libdns library which causes `NoRecordsException` on `2(SERVFAIL)` dns response
DaveRandom/LibDNS#22

**Comment by kelunik** [comment]
This might explain some reports I received...

**Comment by psafarov** [comment]
@kelunik The library seems to be abandoned actually. Could amp group fork it? Just a proposition, maybe there is a better solution

**Comment by bwoebi** [comment]
@psafarov Apparently I have commit rights there, I just merged your PR - thanks :-)

**Comment by kelunik** [comment]
@bwoebi Could you also tag a new version there, please?

**Comment by bwoebi** [comment]
@kelunik I did right after merging the PR: https://github.com/DaveRandom/LibDNS/releases/tag/v2.0.2
