### ISSUE TITLE
Are dotless domains valid?

### ISSUE THREAD

**Issue by Guuzen** [amphp/dns#93]
Didn't find any test that states dotless domains are invalid.
Are they valid?
If yes - then there is a bug, because resolve method [throws exception](https://github.com/amphp/dns/blob/v1.2.0/lib/Rfc1035StubResolver.php#L158) for dotless domains.
If no - maybe test (and probably explicit exception message) that states dotless domains are invalid should be introduced for clarity and stability?

My use case is simple docker development environment where i want to be able to access hosts in same network by containers/services names. They are usually dotless.

**Comment by kelunik** [comment]
They're valid, yes. If the current config doesn't work with a simple Docker setup, we should remove that restriction again.

**Comment by Guuzen** [comment]
This exception occurs on my machine because resolv.conf file has no search line in it.
According to [docker documentation](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/) docker mounts resolv.conf from host machine.
So if host machine has no search line in resolv.conf then an exception will happen otherwise not.
I do not know how often situation with no search line by default happens in popular linux distros (i installed fresh xubuntu 18.04 and there is a search line). But for me it seems like a bug anyway, because in fact docker dns can resolve dotless host without search line.

**Comment by kelunik** [comment]
Yup. Mind opening a PR? :-)
