### ISSUE TITLE
etc/resolve ndots set to 1

### ISSUE THREAD

**Issue by suadhuskic** [amphp/dns#98]
Wondering why its set to 1 ? I'd like to set it to 3 without writing a new resolver.
https://github.com/amphp/dns/blob/master/lib/UnixConfigLoader.php#L21

Is there a way to extend UnixConfigLoader and continue to use Rfc1035StubResolver ?

**Comment by kelunik** [comment]
You can either edit your /etc/resolv.conf, or set RES_OPTIONS in the environment, which can also be done at the start of the script.

```php
putenv('RES_OPTIONS', 'ndots:3');
```
